version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: crm_nginx
    restart: "no"
    ports:
      - "8020:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - crm_network

  php:
    build: ./docker/php
    container_name: crm_php
    restart: "no"
    volumes:
      - ./src:/var/www/html
    networks:
      - crm_network

  mysql:
    image: mysql:8.0
    container_name: crm_mysql
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm_app
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: crm_pass
    volumes:
      - crm_mysql_data:/var/lib/mysql
    networks:
      - crm_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: crm_phpmyadmin
    restart: "no"
    ports:
      - "8021:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - crm_network

  node:
    image: node:20-alpine
    container_name: crm_node
    restart: "no"
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    volumes:
      - ./src:/var/www/html
    command: sh -c "npm install && npm run dev"
    networks:
      - crm_network

volumes:
  crm_mysql_data:

networks:
  crm_network:
    driver: bridge
